### ISSUE TITLE
Provide wheels for linux/arm64 (aarch64)

### ISSUE THREAD

**Issue by benz0li** [y-crdt/ypy#114]
Cross reference: https://github.com/jupyterlab/jupyterlab/issues/13920

**Comment by kafonek** [comment]
Just went and checked if Github hosted runners support linux/arm64 yet. Unfortunately no https://github.com/actions/runner-images/issues/5631

**Comment by davidbrochart** [comment]
Looks like we could use https://github.com/uraimo/run-on-arch-action instead.
