### ISSUE TITLE
M1 wheel?

### ISSUE THREAD

**Issue by sid-kap** [y-crdt/ypy#118]
Are there plans to build a wheel for M1 macs? (Or can I help add this feature?)

The latest version of jupyterlab depends on ypy, which means that now installing jupyterlab on M1 macs tries to build ypy and produces the error:
```
                Cargo, the Rust package manager, is not installed or is not on PATH.
                This package requires Rust and Cargo to compile extensions. Install it through
                the system's package manager or via https://rustup.rs/
```

**Comment by davidbrochart** [comment]
There is a [PR](https://github.com/y-crdt/ypy/pull/115).

**Comment by davidbrochart** [comment]
Ypy v0.6.0 has wheels for ARM-based macOS.
