### ISSUE TITLE
Missing license information on PYPI

### ISSUE THREAD

**Issue by leoleoasd** [y-crdt/ypy#121]
There is no license information for `ypy` and `ypy-websocket` on pypi. 

Other packages:
![image](https://user-images.githubusercontent.com/37735580/220035195-331036fd-38c8-4b05-9527-d78742357a5c.png)

`y-py`:
![image](https://user-images.githubusercontent.com/37735580/220035356-80d7158b-c586-4e60-8bf5-45b0c0cde5cd.png)

This is blocking our company's auto-build system. I would appreciate it if you could fill in your license in pypi.

**Comment by davidbrochart** [comment]
Thanks for reporting @leoleoasd, do you want to open a PR?

**Comment by davidbrochart** [comment]
Fixed in #123.
