### ISSUE TITLE
No pre-built wheel for macOS arm64

### ISSUE THREAD

**Issue by vthemelis** [y-crdt/ypy#132]
I think it makes sense to have a pre-build image for this combination as it becomes more and more popular.

**Comment by davidbrochart** [comment]
It looks like we have wheels for macOS arm64 for Python 3.8 to 3.11: https://pypi.org/project/y-py/0.6.0/#files
What is your Python version?

**Comment by vthemelis** [comment]
Oh, I see. I was using Python 3.7 and assumed that wheels don't exist in general for arm64 after having a look at

https://github.com/y-crdt/ypy/blob/main/.github/workflows/wheels.yml#L28

In that case, I'll close this now.
