### ISSUE TITLE
Provide wheels for Python 3.12

### ISSUE THREAD

**Issue by benz0li** [y-crdt/ypy#145]
Python 3.12 was released yesterday.

Could you release y-py wheels for Python 3.12, too? What is the expected timeframe for this to happen?

**Comment by davidbrochart** [comment]
Done in [v0.6.2](https://pypi.org/project/y-py/0.6.2).

**Comment by benz0li** [comment]
> Done in [v0.6.2](https://pypi.org/project/y-py/0.6.2).

Thank you.
