### ISSUE TITLE
Deleted key instead of updated

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/ypy#29]
I have a strange behavior where Yjs sets `state[dirty] = true`, but when I observe the `state` YMap in y-py I receive an event saying that the `dirty` key was deleted:
```
{'dirty': {'action': 'delete', 'oldValue': False}}
```
The received update was:
```
[26, 1, 1, 144, 236, 139, 150, 12, 6, 168, 144, 236, 139, 150, 12, 4, 1, 120, 1, 144, 236, 139, 150, 12, 1, 4, 1]
```

**Comment by Horusiath** [comment]
This update is strange as it doesn't look like a valid binary payload for either Yjs/Yrs - it simply couldn't be deserialized.

**Comment by davidbrochart** [comment]
Closing as I cannot reproduce it, thanks!
