### ISSUE TITLE
Thread error

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/ypy#34]
I've noticed that since I've been using y-py in the back-end in Jupyter, I have threading issues while exiting with Ctrl-C:
```
Exception ignored in: <module 'threading' from '/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/threading.py", line 1560, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
FATAL: exception not rethrown
Aborted (core dumped)
```
I know that Yrs uses threads, so it might be related.

**Comment by Waidhoferj** [comment]
Ypy isn't thread safe, at least for passing objects between threads. I'm guessing that is causing the issue. Yrs has moved over to using atomics in some areas of the code, so it might be possible to improve Ypy for use in multithreaded applications. Do you have any example code for where the error occurred?

**Comment by davidbrochart** [comment]
The issue doesn't happen when passing ypy objects between threads, but when exiting JupyterLab with Ctrl-C. You can reproduce it with [this branch](https://github.com/jupyterlab/jupyterlab/pull/12360). But as this operation [uses a thread](https://github.com/jupyter-server/jupyter_server/blob/64bfcea7e802216d92f1947120a4e2c8bcf5b286/jupyter_server/serverapp.py#L2034-L2036), maybe it doesn't play well with ypy. All I can say is that it didn't happen before using ypy.

**Comment by Waidhoferj** [comment]
Could possibly be a [PyO3 issue](https://github.com/PyO3/pyo3/issues/1274).

**Comment by Waidhoferj** [comment]
@davidbrochart was this fixed by the time the [branch](https://github.com/jupyterlab/jupyterlab/pull/12360) was merged?

**Comment by davidbrochart** [comment]
Yes, I think this issue disappeared. Thanks!
