### ISSUE TITLE
Wheel for macOS and Python 3.10 is not on Pypi

### ISSUE THREAD

**Issue by jasongrout** [y-crdt/ypy#36]
@agoose77 noticed over in https://github.com/jupyterlab/jupyterlab/issues/12436 that there is no wheel for MacOS Python 3.10 up on pypi: https://pypi.org/project/y-py/#files

Indeed, trying to install in a new Python 3.10 environment on macOS 12.3 (on an m1 chip) leads to errors about not having Cargo (i.e., it picked up the sdist instead of a wheel):

<details>
<summary>Command-line output</summary>
<pre>

$ pip install y-py
Collecting y-py
  Using cached y_py-0.4.3.tar.gz (30 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

</pre>
</details>

**Comment by agoose77** [comment]
Can this be closed now? I see MacOS wheels for 3.10.

**Comment by jasongrout** [comment]
Thanks! Indeed, I can install y-py now.

Unfortunately, JupyterLab requires y-py 0.3.x, which is not published, but I'll take this up at https://github.com/jupyterlab/jupyterlab/issues/12436 to upgrade the dependency y-py.
