### ISSUE TITLE
Attempt to divide by zero

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/ypy#45]
Just posting a ypy error I got today, I don't know what caused it except that it was while removing the only character in a YText and then probably pushing an empty string.
<details>
thread '<unnamed>' panicked at 'attempt to divide by zero', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.7.0/src/block_store.rs:257:28
stack backtrace:
   0:     0x7fd6bb6cc6dd - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fd6bb6cc6dd - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd6bb6cc6dd - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fd6bb6cc6dd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fd6bb6eebdc - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fd6bb6ca2e8 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7fd6bb6ce187 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fd6bb6ce187 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fd6bb6ce187 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7fd6bb6cde50 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7fd6bb6ce8d9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x7fd6bb6ce589 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:586:13
  12:     0x7fd6bb6ccba4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7fd6bb6ce2d9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x7fd6bb621613 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x7fd6bb6214dd - core::panicking::panic::h4241c5ccea17faca
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
  16:     0x7fd6bb678a19 - yrs::transaction::Transaction::commit::h12039726d879d785
  17:     0x7fd6bb62caa2 - std::panicking::try::h647896984698a0a9
  18:     0x7fd6bb64b6b2 - y_py::y_transaction::_::<impl pyo3::impl_::pyclass::PyMethods<y_py::y_transaction::YTransaction> for pyo3::impl_::pyclass::PyClassImplCollector<y_py::y_transaction::YTransaction>>::py_methods::ITEMS::__wrap::hc8edfdcc5059ed2b
  19:     0x564104b44248 - method_vectorcall_FASTCALL_KEYWORDS
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/descrobject.c:405
  20:     0x564104b8bd1b - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  21:     0x564104b8bd1b - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
  22:     0x564104b8bd1b - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
  23:     0x564104b8bd1b - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4198
  24:     0x564104b6efd5 - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  25:     0x564104b6efd5 - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
  26:     0x564104b6efd5 - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
  27:     0x564104b6efd5 - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  28:     0x564104b6efd5 - method_vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/classobject.c:53
  29:     0x564104b8ba14 - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  30:     0x564104b8ba14 - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
  31:     0x564104b8ba14 - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
  32:     0x564104b8ba14 - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4213
  33:     0x564104b6dddd - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  34:     0x564104b6dddd - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
  35:     0x564104b6dddd - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
  36:     0x564104b57366 - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  37:     0x564104b57366 - object_vacall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:734
  38:     0x564104c189c8 - PyObject_CallFunctionObjArgs
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:841
  39:     0x564104c18b55 - property_descr_set
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/descrobject.c:1637
  40:     0x564104b78246 - _PyObject_GenericSetAttrWithDict
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/object.c:1353
  41:     0x564104b78246 - PyObject_GenericSetAttr
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/object.c:1403
  42:     0x564104b78246 - PyObject_SetAttr
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/object.c:1034
  43:     0x564104b8c467 - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:2850
  44:     0x564104b61266 - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  45:     0x564104b61266 - gen_send_ex2
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/genobject.c:213
  46:     0x564104b61266 - PyGen_am_send
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/genobject.c:272
  47:     0x564104b61266 - PyIter_Send
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/abstract.c:2893
  48:     0x564104b8cabf - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:2586
  49:     0x564104b61266 - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  50:     0x564104b61266 - gen_send_ex2
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/genobject.c:213
  51:     0x564104b61266 - PyGen_am_send
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/genobject.c:272
  52:     0x564104b61266 - PyIter_Send
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/abstract.c:2893
  53:     0x7fd6bf75c81b - task_step_impl
                               at /usr/local/src/conda/python-3.10.2/Modules/_asynciomodule.c:2655:22
  54:     0x7fd6bf75c81b - task_step
                               at /usr/local/src/conda/python-3.10.2/Modules/_asynciomodule.c:2952:11
  55:     0x7fd6bf75d09d - task_wakeup
                               at /usr/local/src/conda/python-3.10.2/Modules/_asynciomodule.c:3001:20
  56:     0x564104b43be2 - cfunction_vectorcall_O
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/methodobject.c:516
  57:     0x564104bdb841 - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  58:     0x564104a3e676 - context_run
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/context.c:665
  59:     0x564104af197f - cfunction_vectorcall_FASTCALL_KEYWORDS
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/methodobject.c:446
  60:     0x564104aef21a - PyVectorcall_Call
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:255
  61:     0x564104aef21a - _PyObject_Call
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:290
  62:     0x564104aef21a - PyObject_Call
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:317:12
  63:     0x564104b91367 - do_call_core
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5891
  64:     0x564104b91367 - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4277
  65:     0x564104b6dddd - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  66:     0x564104b6dddd - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
  67:     0x564104b6dddd - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
  68:     0x564104b8bd1b - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  69:     0x564104b8bd1b - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
  70:     0x564104b8bd1b - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
  71:     0x564104b8bd1b - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4198
  72:     0x564104b6dddd - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  73:     0x564104b6dddd - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
  74:     0x564104b6dddd - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
  75:     0x564104b8bd1b - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  76:     0x564104b8bd1b - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
  77:     0x564104b8bd1b - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
  78:     0x564104b8bd1b - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4198
  79:     0x564104b6dddd - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  80:     0x564104b6dddd - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
  81:     0x564104b6dddd - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
  82:     0x564104b8bd1b - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  83:     0x564104b8bd1b - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
  84:     0x564104b8bd1b - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
  85:     0x564104b8bd1b - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4198
  86:     0x564104b6dddd - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  87:     0x564104b6dddd - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
  88:     0x564104b6dddd - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
  89:     0x564104b8bd1b - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  90:     0x564104b8bd1b - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
  91:     0x564104b8bd1b - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
  92:     0x564104b8bd1b - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4198
  93:     0x564104b6dddd - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
  94:     0x564104b6dddd - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
  95:     0x564104b6dddd - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
  96:     0x564104b8bd1b - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
  97:     0x564104b8bd1b - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
  98:     0x564104b8bd1b - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
  99:     0x564104b8bd1b - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4198
 100:     0x564104b6dddd - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
 101:     0x564104b6dddd - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
 102:     0x564104b6dddd - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
 103:     0x564104b8bd1b - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
 104:     0x564104b8bd1b - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
 105:     0x564104b8bd1b - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
 106:     0x564104b8bd1b - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4198
 107:     0x564104b6efd5 - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
 108:     0x564104b6efd5 - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
 109:     0x564104b6efd5 - _PyFunction_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/call.c:342
 110:     0x564104b6efd5 - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
 111:     0x564104b6efd5 - method_vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Objects/classobject.c:53
 112:     0x564104b8ba14 - _PyObject_VectorcallTstate
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:114:11
 113:     0x564104b8ba14 - PyObject_Vectorcall
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/cpython/abstract.h:123
 114:     0x564104b8ba14 - call_function
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5867
 115:     0x564104b8ba14 - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:4213
 116:     0x564104b6cdd9 - _PyEval_EvalFrame
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Include/internal/pycore_ceval.h:46
 117:     0x564104b6cdd9 - _PyEval_Vector
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:5065
 118:     0x564104c246d7 - PyEval_EvalCode
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/ceval.c:1134
 119:     0x564104c24799 - run_eval_code_obj
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/pythonrun.c:1291
 120:     0x564104c4a7a4 - run_mod
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/pythonrun.c:1312
 121:     0x564104c51e69 - pyrun_file
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/pythonrun.c:1208
 122:     0x564104c5201f - _PyRun_SimpleFileObject
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/pythonrun.c:456
 123:     0x564104c52123 - _PyRun_AnyFileObject
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Python/pythonrun.c:90
 124:     0x564104c53018 - pymain_run_file_obj
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Modules/main.c:357
 125:     0x564104c53018 - pymain_run_file
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Modules/main.c:376
 126:     0x564104c53018 - pymain_run_python
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Modules/main.c:591:21
 127:     0x564104c53018 - Py_RunMain
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Modules/main.c:670
 128:     0x564104c53169 - Py_BytesMain
                               at /home/conda/feedstock_root/build_artifacts/python-split_1646754077016/work/Modules/main.c:1090
 129:     0x7fd6c0914d90 - <unknown>
 130:     0x7fd6c0914e40 - __libc_start_main
 131:     0x564104bbcce1 - <unknown>
</details>

**Comment by acnebs** [comment]
I was able to reproduce this by creating a document that had one YText and pushing a single character and then another YText and pushing an empty string. Changing the order avoids the panic.

Repro:
```python
import y_py as Y

d1 = Y.YDoc()
# Create a new YText object in the YDoc
text1 = d1.get_text("text1")
text2 = d1.get_text("text2")
# Start a transaction in order to update the text
with d1.begin_transaction() as txn:
    # Add text contents
    text1.push(txn, "a")
    text2.push(txn, "")

# Create another document
d2 = Y.YDoc()
# Share state with the original document
state_vector = Y.encode_state_vector(d2)
diff = Y.encode_state_as_update(d1, state_vector)
Y.apply_update(d2, diff)

value1 = str(d2.get_text("text1"))
value2 = str(d2.get_text("text2"))

assert value1 == "a"
assert value2 == ""
```
