### ISSUE TITLE
YMapEvent issues

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/ypy#55]
The [documentation](https://ypy.readthedocs.io/en/latest/autoapi/y_py/index.html#y_py.YMapEvent) says:
- "The *target* references the *YText* element that receives the update". It is not a YText but a YMap.
- `keys :List[YMapEventKeyChange]`: it is not a `List` but a `Dict`.
- `delta :List[Dict]`: there is not `delta` attribute.
- `path(self) → List[Union[int, str]]`: it seems to always return an empty list. Also I don't understand the description: "Array of keys and indexes creating a path from root type down to current instance of shared type (accessible via target getter)".

Also, how can we access the `YMapEvent` object? `y_py.YMapEvent` doesn't exist.

**Comment by Waidhoferj** [comment]
@davidbrochart the `path` attribute only shows up when you are fielding an event inside an `observe_deep()` callback. It will show the path from the root to that element. I updated the docs to reflect this. Thanks for bringing that up.
