### ISSUE TITLE
Cannot use non string mapping key

### ISSUE THREAD

**Issue by ksamuel** [y-crdt/ypy#56]
Doing this:

```python
import y_py as Y

d1 = Y.YDoc()
root = d1.get_map('stuff')

with d1.begin_transaction() as txn:
    root.set(txn, 1, 1)
```

Will result in "TypeError: argument 'key': 'int' object cannot be converted to 'PyString'".

However, using any hashable object as a mapping key is a common pattern. ypy should either support it, or raise a more explicit exception and document this behavior.

**Comment by Horusiath** [comment]
ypy doesn't support this behavior, because yrs/yjs don't support non-string keys in YMap either. We were discussing proposal to change that to work over any hashable values, but it's not done yet.

**Comment by ksamuel** [comment]
There may be a way to get this for cheap: allow also bytes to be passed for keys. Since the keys of the rust implementation are turned into UTF8, one could convert any byte using a surrogate escape.

Then we can pickle any non string object into bytes and pass that around. 

I tried to pass a string surrogate escaped utf8 encoded string already, but it complains about it because the underlying implementation doesn't expect it.

If none of that is possible, then changing the error message to state "the implementation doesn't support non string key yet" is the next best thing.

**Comment by Waidhoferj** [comment]
I agree that this would be super useful, but the standard for this feature should definitely come from `ycrdt` to keep the implementation and requirements consistent across language ports. For now `ypy` will hold on this one.
