### ISSUE TITLE
Y.encode_state_vector(ydoc) returns a list

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/ypy#67]
It looks like `Y.encode_state_vector(ydoc)` returns a list. I think it should return bytes now that https://github.com/y-crdt/ypy/pull/62/commits/4d13308d29ff137562748e36f92f66ab0e8a2174 is in.

**Comment by Waidhoferj** [comment]
Fixed in https://github.com/y-crdt/ypy/commit/d63f51c9a18e48e68de6de0bd7e18ecee12b0b6c
