### ISSUE TITLE
Add `YArray.__set_item__`

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/ypy#70]
It looks like a `YArray` has a `__get_item__` but no `__set_item__`, which would be useful.

**Comment by Waidhoferj** [comment]
Using `__set_item__` isn't possible because a transaction is required to change the `YArray`. But I could add a method that functionally does the same thing:
```python
y_array.set(txn, index, value)
```

**Comment by davidbrochart** [comment]
Currently I'm doing a `delete` followed by an `insert`, but yes a `set` would be a nice one-liner.

**Comment by Waidhoferj** [comment]
Talked about this with @Horusiath and @dmonad. A set operation is slightly different than a get + delete and isn't currently supported by yrs or yjs. Simultaneous set operations create something like a last writer wins relationship, with the new value being mutually exclusive to other concurrent sets. Get + delete allows for both users to add values and those to coexist.

I don't think there's a plan currently to add the set operation into yrs.  If there is underlying support for set in the future, I'd definitely add it to the API.

**Comment by davidbrochart** [comment]
Thanks for the details, closing.
